### PR TITLE
Use mutagen to support m4a and mp3

### PR DESCRIPTION
**Pull request by mshick**
I've updated the script to use the newer mutagen module, so that it can support m4a along with mp3. Could also presumably be expanded for flac, etc, but m4a was all I needed.

### CODE REVIEW

**Comment by mshick** [comment]
I did a little more work to get this working via a homebrew install (which also installs the deps). I have the formula over here:

https://github.com/mshick/homebrew-personal/blob/master/Formula/coverlovin.rb

If you're into the mods perhaps you can use this as a starting point for a homebrew release? This is a pretty useful script I think.

**Comment by amorphic** [comment]
Hey there, thanks for the PR!

It looks good, I've been meaning for a while to add mutagen support. Just one thing -  I see you've changed some of the utf-8 encoding/decoding. Why is that? Unfortunately I don't have any unit tests so I've no way of confirming that these are non-breaking changes.

Let me know and I'll merge this.

**Comment by mshick** [comment]
Sure. 

The reason for the utf-8 stuff, which is ugly, is that the mutagen output  all required that encoding step or else it would screw up when I tried to access the props -- they come out as Unicode natively. Encoding that necessitated decoding it for the logger. I tried a few logger tricks to set up a formatter to handle it internally, but had no luck. 

I'm not primarily a python dev, and I found the Unicode handling a bit of a mystery. If you know how to clean that stuff up I'd love to know the tricks, and I can amend the PR. 

I was testing with Björk albums, to ensure the system could handle the non-ascii. What I've submitted was working well there.

**Comment by mshick** [comment]
Sorry, I submitted that last comment via email and it looks like it did some weird quoting, so maybe you didn't see the actual message:

The reason for the utf-8 stuff, which is ugly, is that the mutagen output  all required that encoding step or else it would screw up when I tried to access the props -- they come out as Unicode natively. Encoding that necessitated decoding it for the logger. I tried a few logger tricks to set up a formatter to handle it internally, but had no luck. 

I'm not primarily a python dev, and I found the Unicode handling a bit of a mystery. If you know how to clean that stuff up I'd love to know the tricks, and I can amend the PR.

I was testing with Björk albums, to ensure the system could handle the non-ascii. What I've submitted was working well there.

**Review by amorphic — APPROVED** [review]

**Pull request merged**
